language: python
python:
  - 3.6
  - 3.7
  - 3.8
sudo: false
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - pip install codecov
  - echo "install end"
script:
  - echo "script start"
  - pytest --cov=cointanalysis
  - sh tests/examples.sh
  - echo "script end"
after_success:
  - flake8 cointanalysis
  - codecov
