language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - echo "install end"
before_script:
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov codecov
script:
  - echo "pytest start"
  - sh tests/pytest.sh
  - echo "pytest end"
  - echo "flake8 start"
  - flake8 cointanalysis
  - echo "flake8 end"
after_success:
  - codecov
