[tool.poetry]
name = "cointanalysis"
version = "0.1.0"
description = "Python package for cointegration analysis."
authors = ["Shota Imaki <shota.imaki@icloud.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/simaki/cointanalysis"
homepage = "https://github.com/simaki/cointanalysis"
classifiers = [
  'Intended Audience :: Financial and Insurance Industry',
  'Topic :: Office/Business :: Financial :: Investment',
]
packages = [
  { include = "cointanalysis" },
]

[tool.poetry.dependencies]
python = '^3.6'
numpy = "^1.18.0"
statsmodels = "^0.10.2"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
